Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Action_Amount__c</fullName>
        <label>Actual Action Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agreed_Amount_Base_Amount__c</fullName>
        <label>Agreed Amount Base Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agreed_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agreed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Provided to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Handed over to Ops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Balance_Remaining__c</fullName>
        <formula>Agreed_Amount__c -  Executed_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ET_Status__c</fullName>
        <label>ET Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Executed_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Executed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Executed_Product_Name__c</fullName>
        <label>Executed Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <formula>IF(ISPICKVAL(Type__c,&apos;Life Insurance&apos;) ,&apos;LIfe Insurance&apos;, 
IF(ISPICKVAL(Type__c,&apos;General Insurance&apos;) ,&apos;General Insurance&apos;,IF(ISPICKVAL(Type__c,&apos;Surrender Insurance&apos;) ,&apos;Surrender Insurance&apos;, 
IF(ISPICKVAL(Type__c,&apos;Loan&apos;) ,&apos;Loan&apos;, 
IF(ISPICKVAL(Type__c,&apos;Fixed Deposit&apos;) ,&apos;Fixed Deposit&apos;, 
IF(ISPICKVAL(Type__c,&apos;Bond&apos;) ,&apos;Bond&apos;,
IF((NOT( ISBLANK(Goal__c))),Goal__r.Description__c,&apos;Mutual Fund&apos;)))))))</formula>
        <label>Goal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme_Name_Policy_Name__c</fullName>
        <description>Map Scheme name from Mutual Funds and Policy Name if provided for LI and GI</description>
        <label>Scheme Name/Policy Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suggested_Amount__c</fullName>
        <label>Suggested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FreedomSanboxAntDeploy/src/Freedom Work/24-9-2013/Sandbox Code Backup/Before Refresh/classes/ExecutionTrackerRelatedListController.cls
public with sharing class ExecutionTrackerRelatedListController 
{
	 private DatabaseSOQL dbSOQLObj {get; set;}
	 public Id entityId {get;set;}
	 public List<Execution_Tracker__c> lstET {get;set;}
	 public Id rejectedTrackerId {get;set;}
	 
	 public ExecutionTrackerRelatedListController(ApexPages.StandardController controller)
     {
     	entityId = controller.getId();
     	dbSOQLObj = new DatabaseSOQL();
     	Set<Id> familyIdSet = new Set<Id>(); 
    	List<Account> lstAcc = dbSOQLObj.getFamilyMembers(entityId);
     
   	 	for(Account objAcc : lstAcc)
    	{
      		familyIdSet.add(objAcc.Id);
    	}
    	
     	lstET = [Select Id,Goal_Name__c, Agreed_Amount_Base_Amount__c,Suggested_Amount__c, Scheme_Name_Policy_Name__c, Owner__r.Name, Executed_Amount__c, ET_Status__c, 
     				Balance_Remaining__c, Executed_Product_Name__c,Agreed_Amount__c,Application_Status__c,Actual_Action_Amount__c  
     				From Execution_Tracker__c 
     				where Entity_Name__c IN: familyIdSet and (Application_Status__c = 'Rejected' or Application_Status__c = 'Closed')];
     	
     }
     public pagereference ViewRecords()
	 {
	 	pageReference pageRef = new pageReference('/'+rejectedTrackerId);
        return pageRef;
	 }
}