FreedomSanboxAntDeploy/src/objects/Lead_Platform_User__c.object
<CustomObject>
    <description>Its is the custom Lead object created for standard platform user.</description>
    <fields>
        <fullName>Age__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Age</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>BNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Comm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Engines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar (MKT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar (WS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FP Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web-Onlinepromotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web-XRay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Lead_Source__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This stores lead source required for KPI</description>
    <label>Lead Source for KPI</label>
</CustomObject>

FreedomSanboxAntDeploy/src/Freedom Work/24-9-2013/Sandbox Code Backup/Before Refresh/classes/Test_InsertUpdateDeleteOnTask.cls
//By Aditi for testing Platform User Related Code
//Date : 30/08/12 
@isTest
private class Test_InsertUpdateDeleteOnTask {

    static testMethod void myUnitTest() 
    {
        // TO DO: implement unit test
        List<Task> lstTask = new List<Task>();
    	
    	
    	//======================================For Custom Lead======================================
    	Lead_Platform_User__c Custlead1 = new Lead_Platform_User__c(First_Name__c = 'Platform', Name = 'User', Lead_Status__c = 'Open', Lead_Source__c = 'Web', Mobile__c = '9898989898', Age__c = 23);
    	insert Custlead1;
    	
    	Task testTask = new Task(Status ='Completed',Subject ='Call',WhatId = Custlead1.Id);
        lstTask.add(testTask);
        
        Task testTask1 = new Task(Status ='Completed',Subject ='Call',WhatId = Custlead1.Id);
        lstTask.add(testTask1);
    
    	//======================================For Custom Lead======================================
    
        Lead Lead_1 = new Lead(FirstName = 'Original', LastName = 'Lead',Status = 'Open',LeadSource = 'Web', MobilePhone = '9898989898',Platform_User_Lead__c = Custlead1.Id,  Age__c = 23);
    	insert Lead_1;
    	
    	Task testTask2 = new Task(Status ='Completed',Subject ='Call',WhoId = Lead_1.Id);
        lstTask.add(testTask2);
        
        Task testTask3 = new Task(Status ='Completed',Subject ='Call',WhoId = Lead_1.Id);
        lstTask.add(testTask3);
       
      	insert lstTask;
      	
      	
      	delete testTask1; //Custom 
      	delete testTask3; //Standard
      	
    }
    
    
    
}